[tools]
rojo = "rojo-rbx/rojo@7.3.0"
remodel = "rojo-rbx/remodel@0.10.0"
selene = "Kampfkarren/selene@0.24.0"
stylua = "johnnymorganz/stylua@0.14.2"
tarmac = "Roblox/tarmac@0.7.0"
wally = "UpliftGames/wally@0.3.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"