[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.0.0" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
selene = { source = "Kampfkarren/selene", version = "0.15.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.11.3" }
tarmac = { source = "Roblox/tarmac", version = "0.7.0" }