std = "roblox"
exclude = ["Packages"]

[rules]
# unused_variable = "allow"
# undefined_variable = "allow"
# multiple_statements = "allow"
# incorrect_standard_library_use = "allow"

[config]
unused_variable = { ignore_pattern = "(^_|rbx|Array|Set|Dictionary)", allow_unused_self=true }