[package]
name = "metauni/metaboard"
version = "1.5.0-rc1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["lib", "lib/*", "assets", "assets/Assets.lua", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Feather = "blinkybool/feather@0.2.0"
Roact = "roblox/roact@1.4.4"
Sift = "csqrl/sift@0.0.4"
Promise = "evaera/promise@4.0.0"
