[package]
name = "metauni/metaboard"
version = "1.5.1-rc04"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["lib", "lib/*", "assets", "assets/Assets.lua", "Util", "Util/**", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Feather = "blinkybool/feather@0.2.1"
Roact = "roblox/roact@1.4.4"
Sift = "csqrl/sift@0.0.4"
Promise = "evaera/promise@4.0.0"
t = "osyrisrblx/t@3.0.0"