-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	["eraser-deselected"] = "rbxassetid://9278421842",
	["eraser-large-deselected"] = "rbxassetid://9284989060",
	["eraser-large-selected"] = "rbxassetid://9284989120",
	["eraser-medium-deselected"] = "rbxassetid://9284989194",
	["eraser-medium-selected"] = "rbxassetid://9284989298",
	["eraser-selected"] = "rbxassetid://9278421896",
	["eraser-small-deselected"] = "rbxassetid://9284989407",
	["eraser-small-selected"] = "rbxassetid://9284989669",
	["expand-down"] = "rbxassetid://9285467282",
	["pen-deselected"] = "rbxassetid://9278018574",
	["pen-selected"] = "rbxassetid://9278018628",
	redo = "rbxassetid://9276894292",
	["straightedge-deselected"] = "rbxassetid://9278385380",
	["straightedge-selected"] = "rbxassetid://9278137537",
	undo = "rbxassetid://9276894383",
}