name: CI

# This action triggers on a push, pull request and manual trigger.
on:
  push:
  pull_request:
  workflow_dispatch:

# Jobs to perform on trigger.
jobs:
  check-license-headers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Headers
      uses: kt3k/license_checker@v1.0.6
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Initialize Aftman
        uses: ok-nick/setup-aftman@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selene
        run: selene src
